# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:24:50+00:00



import argparse
import json
import os
from datetime import date as date_aliased
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Header, Query
from pydantic import conint, constr

from models import (
    Error400,
    Error500,
    GetFlightOffersQuery,
    ShoppingFlightOffersGetResponse,
    ShoppingFlightOffersPostResponse,
    TravelClass,
)

app = MCPProxy(
    description='\nBefore using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token. \n\nPlease also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).',
    title='Flight Offers Search',
    version='2.2.0',
    servers=[{'url': 'https://test.api.amadeus.com/v2'}],
)


@app.get('/shopping/flight-offers', tags=['flight_offer_management'])
def get_flight_offers(
    origin_location_code: constr(pattern=r'[A-Z]{3}') = Query(
        ..., alias='originLocationCode'
    ),
    destination_location_code: constr(pattern=r'[A-Z]{3}') = Query(
        ..., alias='destinationLocationCode'
    ),
    departure_date: date_aliased = Query(..., alias='departureDate'),
    return_date: Optional[date_aliased] = Query(None, alias='returnDate'),
    adults: conint(ge=1, le=9) = 1,
    children: Optional[conint(ge=0, le=9)] = None,
    infants: Optional[conint(ge=0, le=9)] = None,
    travel_class: Optional[TravelClass] = Query(None, alias='travelClass'),
    included_airline_codes: Optional[constr(pattern=r'[0-9A-Z]{2}')] = Query(
        None, alias='includedAirlineCodes'
    ),
    excluded_airline_codes: Optional[constr(pattern=r'[0-9A-Z]{2}')] = Query(
        None, alias='excludedAirlineCodes'
    ),
    non_stop: Optional[bool] = Query(False, alias='nonStop'),
    currency_code: Optional[constr(pattern=r'[A-Z]{3}')] = Query(
        None, alias='currencyCode'
    ),
    max_price: Optional[conint(ge=1)] = Query(None, alias='maxPrice'),
    max: Optional[conint(ge=1)] = 250,
):
    """
    Return list of Flight Offers based on searching criteria.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post('/shopping/flight-offers', tags=['flight_offer_management'])
def search_flight_offers(
    x__h_t_t_p__method__override: str = Header(..., alias='X-HTTP-Method-Override'),
    body: GetFlightOffersQuery = ...,
):
    """
    Return list of Flight Offers based on posted searching criteria.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
