# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:24:50+00:00

from __future__ import annotations

from datetime import date as date_aliased
from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import AnyUrl, BaseModel, Field, RootModel, confloat, constr


class AdditionalServiceType(Enum):
    CHECKED_BAGS = 'CHECKED_BAGS'
    MEALS = 'MEALS'
    SEATS = 'SEATS'
    OTHER_SERVICES = 'OTHER_SERVICES'


class AircraftEntry(BaseModel):
    key: Optional[str] = None


class AircraftEquipment(BaseModel):
    code: Optional[constr(pattern=r'[a-zA-Z0-9]{3}')] = Field(
        None,
        description='IATA aircraft code (http://www.flugzeuginfo.net/table_accodes_iata_en.php)\n',
        examples=['318'],
    )


class BaggageAllowance(BaseModel):
    quantity: Optional[int] = Field(
        None, description='Total number of units', examples=[1]
    )
    weight: Optional[int] = Field(
        None, description='Weight of the baggage allowance', examples=[20]
    )
    weightUnit: Optional[str] = Field(
        None, description='Code to qualify unit as pounds or kilos', examples=['KG']
    )


class CarrierEntry(BaseModel):
    key: Optional[str] = None


class OneWayCombination(BaseModel):
    flightOfferIds: Optional[List[str]] = None
    originDestinationId: Optional[str] = None


class CollectionMeta(BaseModel):
    count: Optional[int] = Field(None, examples=[1])
    oneWayCombinations: Optional[List[OneWayCombination]] = None


class Links(BaseModel):
    first: Optional[AnyUrl] = Field(
        None, examples=['https://test.api.amadeus.com/v1/area/resources?...']
    )
    last: Optional[AnyUrl] = Field(
        None, examples=['https://test.api.amadeus.com/v1/area/resources?...']
    )
    next: Optional[AnyUrl] = Field(
        None, examples=['https://test.api.amadeus.com/v1/area/resources?...']
    )
    previous: Optional[AnyUrl] = Field(
        None, examples=['https://test.api.amadeus.com/v1/area/resources?...']
    )
    self: Optional[AnyUrl] = Field(
        None, examples=['https://test.api.amadeus.com/v1/area/resources?...']
    )
    up: Optional[AnyUrl] = Field(
        None, examples=['https://test.api.amadeus.com/v1/area/resources?...']
    )


class CollectionMetaLink(BaseModel):
    count: Optional[int] = Field(None, examples=[1])
    links: Optional[Links] = Field(
        None,
        examples=[
            {'self': 'https://test.api.amadeus.com/v1/area/resources?param=value'}
        ],
        title='CollectionLinks',
    )


class Coverage(Enum):
    MOST_SEGMENTS = 'MOST_SEGMENTS'
    AT_LEAST_ONE_SEGMENT = 'AT_LEAST_ONE_SEGMENT'
    ALL_SEGMENTS = 'ALL_SEGMENTS'


class CurrencyEntry(BaseModel):
    key: str = Field(..., examples=['Euro'])


class DateTimeRange(BaseModel):
    date: date_aliased = Field(
        ...,
        description='Dates are specified in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-DD format, e.g. 2018-12-25',
        examples=['2018-09-22'],
    )
    dateWindow: Optional[constr(pattern=r'^[MPI][1-3]D')] = Field(
        None,
        description='Either 1, 2 or 3 extra days around the local date (IxD for +/- x days - Ex: I3D), Either 1 to 3 days after the local date (PxD for +x days - Ex: P3D), or 1 to 3 days before the local date (MxD for -x days - Ex: M3D)\n\nCan not be combined with "originRadius" or "destinationRadius".\n',
        examples=['I3D'],
    )
    time: Optional[str] = Field(
        None,
        description='Local time. hh:mm:ss format, e.g 10:30:00',
        examples=['10:30:00'],
    )
    timeWindow: Optional[constr(pattern=r'^([1-9]|10|11|12)H')] = Field(
        None,
        description='1 to 12 hours around (both +and -) the local time. Possibly limited by the number of extra days when specified, i.e.  in some situations, it may not be used to exceed the maximum date range. [1-12]H format, e.g. 6H\n\nCan not be combined with "originRadius" or "destinationRadius".\n',
        examples=['2H'],
    )


class ExtendedPricingOptions(BaseModel):
    includedCheckedBagsOnly: Optional[bool] = Field(
        None,
        description='If true, returns the flight-offers with included checked bags only',
        examples=[True],
    )


class AdditionalService(BaseModel):
    amount: Optional[str] = Field(None, examples=['332.70'])
    type: Optional[AdditionalServiceType] = None


class FeeType(Enum):
    TICKETING = 'TICKETING'
    FORM_OF_PAYMENT = 'FORM_OF_PAYMENT'
    SUPPLIER = 'SUPPLIER'


class AllotmentDetails(BaseModel):
    tourName: Optional[str] = None
    tourReference: Optional[str] = None


class FlightOfferSource(Enum):
    GDS = 'GDS'


class Source(BaseModel):
    example: Optional[str] = Field(
        None, description='a string indicating an example of the right value'
    )
    parameter: Optional[str] = Field(
        None,
        description='a string indicating which URI query parameter caused the issue',
    )
    pointer: Optional[str] = Field(
        None,
        description='a JSON Pointer [RFC6901] to the associated entity in the request document',
    )


class Issue(BaseModel):
    code: Optional[int] = Field(None, description='an application-specific error code')
    detail: Optional[str] = Field(None, description='explanation of the error')
    source: Optional[Source] = Field(
        None,
        description='an object containing references to the source of the error',
        title='Issue_Source',
    )
    status: Optional[int] = Field(
        None, description='the HTTP status code applicable to this error'
    )
    title: Optional[str] = Field(None, description='a short summary of the error')


class LocationEntry(BaseModel):
    key: str


class LocationValue(BaseModel):
    cityCode: Optional[str] = Field(
        None, description='City code associated to the airport', examples=['PAR']
    )
    countryCode: Optional[str] = Field(
        None, description='Country code of the airport', examples=['FR']
    )


class OperatingFlight(BaseModel):
    carrierCode: Optional[constr(min_length=1, max_length=2)] = Field(
        None, description='providing the airline / carrier code', examples=['DL']
    )


class OriginDestination(BaseModel):
    alternativeDestinationsCodes: Optional[List[str]] = Field(
        None,
        description='Set of alternative destination location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.',
        max_length=2,
        min_length=1,
    )
    alternativeOriginsCodes: Optional[List[str]] = Field(
        None,
        description='Set of alternative origin location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.',
        examples=[['LON', 'MUC']],
        max_length=2,
        min_length=1,
    )
    arrivalDateTimeRange: Optional[DateTimeRange] = None
    departureDateTimeRange: Optional[DateTimeRange] = None
    destinationLocationCode: Optional[str] = Field(
        None,
        description='Destination location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.',
        examples=['NYC'],
    )
    destinationRadius: Optional[float] = Field(
        None,
        description='Include other possible locations around the point, located less than this distance in kilometers away. Max:300\n\nCan not be combined with "dateWindow" or "timeWindow".\n',
        examples=[200],
    )
    excludedConnectionPoints: Optional[List[str]] = Field(
        None,
        description='List of excluded connections points. Any FlightOffer with these connections points will be present in response. Currently, only the locations defined in IATA are supported. Used only by the AMADEUS provider',
        examples=[['MRS']],
        max_length=3,
        min_length=1,
    )
    id: Optional[str] = Field(None, examples=[1])
    includedConnectionPoints: Optional[List[str]] = Field(
        None,
        description='List of included connections points. When an includedViaPoints option is specified, all FlightOffer returned must at least go via this Connecting Point. Currently, only the locations defined in IATA are supported. Used only by the AMADEUS provider',
        examples=[['MRS']],
        max_length=2,
        min_length=1,
    )
    originLocationCode: Optional[str] = Field(
        None,
        description='Origin location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.',
        examples=['PAR'],
    )
    originRadius: Optional[float] = Field(
        None,
        description='Include other possible locations around the point, located less than this distance in kilometers away. Max:300\n\nCan not be combined with "dateWindow" or "timeWindow".\n',
        examples=[200],
    )


class OriginalFlightEndPoint(BaseModel):
    iataCode: Optional[str] = Field(
        None,
        description='[IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)',
        examples=['JFK'],
    )
    terminal: Optional[str] = Field(
        None, description='terminal name / number', examples=['T2']
    )


class OriginalFlightStop(BaseModel):
    duration: Optional[str] = Field(
        None,
        description='stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M',
        examples=['PT2H10M'],
    )
    iataCode: Optional[str] = Field(
        None,
        description='[IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)',
        examples=['JFK'],
    )


class PricingOptionsFareTypeEnum(Enum):
    PUBLISHED = 'PUBLISHED'
    NEGOTIATED = 'NEGOTIATED'
    CORPORATE = 'CORPORATE'


class PricingOptionsFareType(RootModel[List[PricingOptionsFareTypeEnum]]):
    root: List[PricingOptionsFareTypeEnum] = Field(
        ..., description='type of fare of the flight-offer', examples=[['PUBLISHED']]
    )


class AdditionalInformation(BaseModel):
    brandedFares: Optional[bool] = Field(
        None,
        description='If true, returns the fare family name for each flight-offer which supports fare family',
        examples=[True],
    )
    chargeableCheckedBags: Optional[bool] = Field(
        None,
        description='If true, returns the price of the first additional bag when the airline is an "Amadeus Ancillary Services" member.',
        examples=[True],
    )


class CarrierRestrictions(BaseModel):
    blacklistedInEUAllowed: Optional[bool] = Field(
        None,
        description='This flag enable/disable filtering of blacklisted airline by EU. The list of the banned airlines is published in the Official Journal of the European Union, where they are included as annexes A and B to the Commission Regulation. The blacklist of an airline can concern all its flights or some specific aircraft types pertaining to the airline',
    )
    excludedCarrierCodes: Optional[List[str]] = Field(
        None,
        description='This option ensures that the system will only consider these airlines.',
        max_length=99,
        min_length=1,
    )
    includedCarrierCodes: Optional[List[str]] = Field(
        None,
        description='This option ensures that the system will only consider these airlines.',
        max_length=99,
        min_length=1,
    )


class ConnectionRestriction(BaseModel):
    airportChangeAllowed: Optional[bool] = Field(
        None, description='Allow to change airport during connection', examples=[False]
    )
    maxNumberOfConnections: Optional[float] = Field(
        None,
        description='The maximal number of connections for each itinerary. Value can be 0, 1 or 2.',
        examples=[2],
    )
    technicalStopsAllowed: Optional[bool] = Field(
        None,
        description='This option allows the single segment to have one or more intermediate stops (technical stops).',
        examples=[True],
    )


class ServiceName(Enum):
    PRIORITY_BOARDING = 'PRIORITY_BOARDING'
    AIRPORT_CHECKIN = 'AIRPORT_CHECKIN'


class SliceDiceIndicator(Enum):
    LOCAL_AVAILABILITY = 'LOCAL_AVAILABILITY'
    SUB_OD_AVAILABILITY_1 = 'SUB_OD_AVAILABILITY_1'
    SUB_OD_AVAILABILITY_2 = 'SUB_OD_AVAILABILITY_2'


class Tax(BaseModel):
    amount: Optional[str] = Field(None, examples=['332.70'])
    code: Optional[str] = Field(None, examples=['MX'])


class TravelClass(Enum):
    ECONOMY = 'ECONOMY'
    PREMIUM_ECONOMY = 'PREMIUM_ECONOMY'
    BUSINESS = 'BUSINESS'
    FIRST = 'FIRST'


class TravelerPricingFareOption(Enum):
    STANDARD = 'STANDARD'
    INCLUSIVE_TOUR = 'INCLUSIVE_TOUR'
    SPANISH_MELILLA_RESIDENT = 'SPANISH_MELILLA_RESIDENT'
    SPANISH_CEUTA_RESIDENT = 'SPANISH_CEUTA_RESIDENT'
    SPANISH_CANARY_RESIDENT = 'SPANISH_CANARY_RESIDENT'
    SPANISH_BALEARIC_RESIDENT = 'SPANISH_BALEARIC_RESIDENT'
    AIR_FRANCE_METROPOLITAN_DISCOUNT_PASS = 'AIR_FRANCE_METROPOLITAN_DISCOUNT_PASS'
    AIR_FRANCE_DOM_DISCOUNT_PASS = 'AIR_FRANCE_DOM_DISCOUNT_PASS'
    AIR_FRANCE_COMBINED_DISCOUNT_PASS = 'AIR_FRANCE_COMBINED_DISCOUNT_PASS'
    AIR_FRANCE_FAMILY = 'AIR_FRANCE_FAMILY'
    ADULT_WITH_COMPANION = 'ADULT_WITH_COMPANION'
    COMPANION = 'COMPANION'


class TravelerType(Enum):
    ADULT = 'ADULT'
    CHILD = 'CHILD'
    SENIOR = 'SENIOR'
    YOUNG = 'YOUNG'
    HELD_INFANT = 'HELD_INFANT'
    SEATED_INFANT = 'SEATED_INFANT'
    STUDENT = 'STUDENT'


class Co2Emission(BaseModel):
    cabin: Optional[TravelClass] = None
    weight: Optional[int] = Field(
        None,
        description='Weight of Co2 emitted for the concerned segment',
        examples=[90],
    )
    weightUnit: Optional[str] = Field(
        None, description='Code to qualify unit as pounds or kilos', examples=['KG']
    )


class Dictionaries(BaseModel):
    aircraft: Optional[AircraftEntry] = None
    carriers: Optional[CarrierEntry] = None
    currencies: Optional[CurrencyEntry] = None
    locations: Optional[LocationEntry] = None


class Error400(BaseModel):
    errors: List[Issue]


class Error500(BaseModel):
    errors: List[Issue]


class Fee(BaseModel):
    amount: Optional[str] = Field(None, examples=['332.70'])
    type: Optional[FeeType] = None


class FlightEndPoint(OriginalFlightEndPoint):
    at: Optional[datetime] = Field(
        None,
        description='local date and time in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00',
        examples=['2017-10-23T20:00:00'],
    )


class PricingOptions(BaseModel):
    fareType: Optional[PricingOptionsFareType] = None
    includedCheckedBagsOnly: Optional[bool] = Field(
        None,
        description='If true, returns the flight-offers with included checked bags only',
        examples=[True],
    )
    noPenaltyFare: Optional[bool] = Field(
        None,
        description='If true, returns the flight-offers with no penalty fares only',
        examples=[True],
    )
    noRestrictionFare: Optional[bool] = Field(
        None,
        description='If true, returns the flight-offers with no restriction fares only',
        examples=[True],
    )
    refundableFare: Optional[bool] = Field(
        None,
        description='If true, returns the flight-offers with refundable fares only',
        examples=[True],
    )


class AdditionalServices(BaseModel):
    chargeableCheckedBags: Optional[BaggageAllowance] = None
    chargeableSeatNumber: Optional[constr(pattern=r'[1-9][0-9]{0,2}[A-Z]?')] = Field(
        None, description='seat number', examples=['33D']
    )
    otherServices: Optional[List[ServiceName]] = Field(
        None, description='Other services to add', examples=[['PRIORITY_BOARDING']]
    )


class FareDetailsBySegmentItem(BaseModel):
    additionalServices: Optional[AdditionalServices] = Field(
        None, title='AdditionalServicesRequest'
    )
    allotmentDetails: Optional[AllotmentDetails] = Field(None, title='AllotmentDetails')
    brandedFare: Optional[str] = Field(
        None,
        description='The name of the Fare Family corresponding to the fares. Only for the GDS provider and if the airline has fare families filled',
        examples=['LIGHTONE'],
    )
    cabin: Optional[TravelClass] = None
    class_: Optional[constr(pattern=r'[A-Z]{1}')] = Field(
        None,
        alias='class',
        description='The code of the booking class, a.k.a. class of service or Reservations/Booking Designator (RBD)',
        examples=['A'],
    )
    fareBasis: Optional[constr(pattern=r'[[A-Z0-9]{1,18}')] = Field(
        None,
        description='Fare basis specifying the rules of a fare. Usually, though not always, is composed of the booking class code followed by a set of letters and digits representing other characteristics of the ticket, such as refundability, minimum stay requirements, discounts or special promotional elements.',
        examples=['ANNNNF4K'],
    )
    includedCheckedBags: Optional[BaggageAllowance] = None
    isAllotment: Optional[bool] = Field(
        None,
        description='True if the corresponding booking class is in an allotment',
        examples=[True],
    )
    segmentId: str = Field(..., description='Id of the segment', examples=['1'])
    sliceDiceIndicator: Optional[SliceDiceIndicator] = None


class FlightStop(OriginalFlightStop):
    arrivalAt: Optional[datetime] = Field(
        None,
        description='arrival at the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00',
        examples=['2017-10-23T20:00:00'],
    )
    departureAt: Optional[datetime] = Field(
        None,
        description='departure from the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm:ss format, e.g. 2017-02-10T20:40:00',
        examples=['2017-10-23T20:00:00'],
    )


class Price(BaseModel):
    base: Optional[str] = Field(
        None, description='Amount without taxes', examples=['632.70']
    )
    currency: Optional[str] = Field(None, examples=['USD'])
    fees: Optional[List[Fee]] = Field(None, description='List of applicable fees')
    refundableTaxes: Optional[str] = Field(
        None,
        description='The amount of taxes which are refundable',
        examples=['200.00'],
    )
    taxes: Optional[List[Tax]] = None
    total: Optional[str] = Field(
        None, description='Total amount paid by the user', examples=['932.70']
    )


class CabinRestriction(BaseModel):
    cabin: Optional[TravelClass] = None
    coverage: Optional[Coverage] = None
    originDestinationIds: Optional[List[str]] = Field(
        None,
        description='The list of originDestination identifiers for which the cabinRestriction applies',
        examples=[[1, 2]],
        title='originDestinationIds',
    )


class FlightFilters(BaseModel):
    busSegmentAllowed: Optional[bool] = Field(
        None,
        description='This flag enable/disable filtering of bus segment',
        examples=[True],
    )
    cabinRestrictions: Optional[List[CabinRestriction]] = Field(
        None,
        description='Restriction towards cabins.',
        max_length=6,
        min_length=1,
        title='CabinRestrictions',
    )
    carrierRestrictions: Optional[CarrierRestrictions] = Field(
        None, description='Restriction towards carriers.', title='CarrierRestrictions'
    )
    connectionRestriction: Optional[ConnectionRestriction] = Field(
        None,
        description='Restriction towards number of connections.',
        title='ConnectionRestriction',
    )
    crossBorderAllowed: Optional[bool] = Field(
        None,
        description='Allows to search a location outside the borders when a radius around a location is specified. Default is false.',
        examples=[False],
    )
    maxFlightTime: Optional[float] = Field(
        None,
        description='This option allows to modify the value for the Elapsed Flying Time (EFT) masterPricer option',
        examples=[200],
    )
    moreOvernightsAllowed: Optional[bool] = Field(
        None,
        description='This flag enables/disables the possibility to have more overnight flights in Low Fare Search',
        examples=[False],
    )
    railSegmentAllowed: Optional[bool] = Field(
        None,
        description='This flag enable/disable filtering of rail segment (TGV AIR, RAIL ...)',
        examples=[True],
    )
    returnToDepartureAirport: Optional[bool] = Field(
        None,
        description='This option force to retrieve flight-offer with a departure and a return in the same airport',
        examples=[False],
    )


class SearchCriteria(BaseModel):
    addOneWayOffers: Optional[bool] = Field(
        None,
        description='This option allows activate the one-way combinable feature',
        examples=[True],
    )
    additionalInformation: Optional[AdditionalInformation] = Field(
        None, title='AdditionalInformation'
    )
    allowAlternativeFareOptions: Optional[bool] = Field(
        None,
        description='This option allows to default to a standard fareOption if no offers are found for the selected fareOption.',
        examples=[True],
    )
    excludeAllotments: Optional[bool] = Field(
        None,
        description='This option allows to exclude the isAllotment flag associated to a booking class in the search response when it exist.',
        examples=[False],
    )
    flightFilters: Optional[FlightFilters] = Field(None, title='FlightFilters')
    maxFlightOffers: Optional[float] = Field(
        250,
        description='Maximum number of flight offers returned (Max 250)',
        examples=[250],
    )
    maxPrice: Optional[int] = Field(
        None,
        description='maximum price per traveler. By default, no limit is applied. If specified, the value should be a positive number with no decimals',
        examples=[100],
    )
    oneFlightOfferPerDay: Optional[bool] = Field(
        None,
        description='Requests the system to find at least one flight-offer per day, if possible, when a range of dates is specified. Default is false.',
        examples=[True],
    )
    pricingOptions: Optional[ExtendedPricingOptions] = None


class Traveler(BaseModel):
    associatedAdultId: Optional[str] = Field(
        None,
        description='if type="HELD_INFANT", corresponds to the adult travelers\'s id who will share the seat',
    )
    id: str = Field(..., examples=[1])
    travelerType: TravelerType


class ExtendedPrice(Price):
    additionalServices: Optional[List[AdditionalService]] = Field(
        None, title='AdditionalServices'
    )
    billingCurrency: Optional[str] = Field(
        None,
        description='Currency of the payment. It may be different than the requested currency',
        examples=['EUR'],
    )
    grandTotal: Optional[str] = Field(
        None,
        description='Total amount paid by the user (including fees and selected additional services).',
        examples=['987.00'],
    )
    margin: Optional[str] = Field(
        None,
        description='BOOK step ONLY - The price margin percentage (plus or minus) that the booking can tolerate. When set to 0, then no price magin is tolerated.',
        examples=['1.00'],
    )


class TravelerPricing(BaseModel):
    associatedAdultId: Optional[str] = Field(
        None,
        description='if type="HELD_INFANT", corresponds to the adult traveler\'s id who will share the seat',
    )
    fareDetailsBySegment: List[FareDetailsBySegmentItem] = Field(
        ..., max_length=18, min_length=1
    )
    fareOption: TravelerPricingFareOption
    price: Optional[Price] = None
    travelerId: str = Field(..., description='Id of the traveler', examples=['1'])
    travelerType: TravelerType


class FlightSegment(BaseModel):
    aircraft: Optional[AircraftEquipment] = None
    arrival: Optional[FlightEndPoint] = None
    carrierCode: Optional[constr(min_length=1, max_length=2)] = Field(
        None, description='providing the airline / carrier code', examples=['DL']
    )
    departure: Optional[FlightEndPoint] = None
    duration: Optional[str] = Field(
        None,
        description='stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M',
        examples=['PT2H10M'],
    )
    number: Optional[constr(min_length=1, max_length=4)] = Field(
        None,
        description='the flight number as assigned by the carrier',
        examples=['212'],
    )
    operating: Optional[OperatingFlight] = None
    stops: Optional[List[FlightStop]] = Field(
        None,
        description='information regarding the different stops composing the flight segment. E.g. technical stop, change of gauge...',
    )


class GetFlightOffersQuery(BaseModel):
    currencyCode: Optional[str] = Field(
        None,
        description='The currency code, as defined in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217), to reflect the currency in which this amount is expressed.',
        examples=['EUR'],
    )
    originDestinations: List[OriginDestination] = Field(
        ...,
        description='Origins and Destinations must be properly ordered in time (chronological order in accordance with the timezone of each location) to describe the journey consistently. Dates and times must not be past nor more than 365 days in the future, according to provider settings.Number of Origins and Destinations must not exceed the limit defined in provider settings.',
        max_length=6,
        min_length=1,
        title='originDestinations',
    )
    searchCriteria: Optional[SearchCriteria] = None
    sources: List[FlightOfferSource] = Field(
        ...,
        description='Allows enable one or more sources. If present in the list, these sources will be called by the system.',
        min_length=1,
        title='sources',
    )
    travelers: List[Traveler] = Field(
        ..., max_length=18, min_length=1, title='travelers'
    )


class Segment(FlightSegment):
    blacklistedInEU: Optional[bool] = Field(
        None,
        description='When the flight has a marketing or/and operating airline that is identified as blacklisted by the European Commission. \n\nTo improve travel safety, the European Commission regularly updates the list of the banned carriers from operating in Europe. It allows any Travel Agency located in the European Union to easily identify and hide any travel recommendation based on some unsafe airlines. \nThe [list of the banned airlines](https://ec.europa.eu/transport/sites/transport/files/air-safety-list_en.pdf) is published in the Official Journal of the European Union, where they are included as annexes A and B to the Commission Regulation. The blacklist of an airline can concern all its flights or some specific aircraft types pertaining to the airline   \n',
        examples=[False],
    )
    co2Emissions: Optional[List[Co2Emission]] = Field(
        None, description='Co2 informations', min_length=1
    )
    id: Optional[str] = Field(None, description='Id of the segment', examples=[1])
    numberOfStops: Optional[int] = Field(
        None, description='Number of stops', examples=[0]
    )


class Itinerary(BaseModel):
    duration: Optional[str] = Field(
        None,
        description='duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M for a duration of 2h10m',
        examples=['PT2H10M'],
    )
    segments: List[Segment] = Field(..., max_length=9, min_length=1, title='Segments')


class FlightOffer(BaseModel):
    disablePricing: Optional[bool] = Field(
        None,
        description='BOOK step ONLY - If true, allows to book a PNR without pricing. Only for the source "GDS"',
        examples=[False],
    )
    id: str = Field(..., description='Id of the flight offer', examples=['1'])
    instantTicketingRequired: Optional[bool] = Field(
        None,
        description='If true, inform that a ticketing will be required at booking step.',
        examples=[False],
    )
    itineraries: Optional[List[Itinerary]] = Field(None, max_length=250, min_length=1)
    lastTicketingDate: Optional[str] = Field(
        None,
        description='If booked on the same day as the search (with respect to timezone), this flight offer is guaranteed to be thereafter valid for ticketing until this date (included). Unspecified when it does not make sense for this flight offer (e.g. no control over ticketing once booked). YYYY-MM-DD format, e.g. 2019-06-07',
        examples=['2018-06-19T00:00:00.000Z'],
    )
    nonHomogeneous: Optional[bool] = Field(
        None,
        description='If true, upon completion of the booking, this pricing solution is expected to yield multiple records (a record contains booking information confirmed and stored, typically a Passenger Name Record (PNR), in the provider GDS or system)',
        examples=[False],
    )
    numberOfBookableSeats: Optional[confloat(ge=1.0, le=9.0)] = Field(
        None,
        description='Number of seats bookable in a single request. Can not be higher than 9.',
        examples=[9],
    )
    oneWay: Optional[bool] = Field(
        None,
        description='If true, the flight offer fulfills only one originDestination and has to be combined with other oneWays to complete the whole journey.',
        examples=[False],
    )
    paymentCardRequired: Optional[bool] = Field(
        None,
        description='If true, a payment card is mandatory to book this flight offer',
        examples=[False],
    )
    price: Optional[ExtendedPrice] = None
    pricingOptions: Optional[PricingOptions] = Field(None, title='PricingOptions')
    source: Optional[FlightOfferSource] = None
    travelerPricings: Optional[List[TravelerPricing]] = Field(
        None,
        description='Fare information for each traveler/segment',
        max_length=18,
        min_length=1,
        title='TravelerPricings',
    )
    type: str = Field(..., description='the resource name', examples=['flight-offer'])
    validatingAirlineCodes: Optional[List[str]] = Field(
        None,
        description='This option ensures that the system will only consider these airlines.',
        examples=[['AF']],
        max_length=9,
        min_length=1,
    )


class ShoppingFlightOffersGetResponse(BaseModel):
    data: List[FlightOffer]
    dictionaries: Optional[Dictionaries] = None
    meta: Optional[CollectionMetaLink] = None
    warnings: Optional[List[Issue]] = None


class ShoppingFlightOffersPostResponse(BaseModel):
    data: List[FlightOffer]
    dictionaries: Optional[Dictionaries] = None
    meta: Optional[CollectionMeta] = None
    warnings: Optional[List[Issue]] = None
